### ISSUE TITLE
Приделать партнерку к оплате и исправить стоимость оплаты

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#15]
http://qwertypay.com/ - вот бесплатно можно прикрутить эту партнерку, условия надо обдумать

**Comment by ilyalyo** [comment]
исправить стоимость оплаты
ты имеешь ввиду сделать 790 в месяц?

**Comment by Zoruf** [comment]
не только, там еще надо дописать текста со скидками и тд, те какие скидки дают 3 и шесть мес, ну я скинул в вк псд повторно, где есть стоаница покупки

**Comment by gitromand** [comment]
Работаем с e-autopay.com

**Comment by gitromand** [comment]
Теперь имеем свою партнёрку, проценты можно выставлять и т.д.
