### ISSUE TITLE
Проблема у чела

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#28]
air_jordan_moscow
Выдает ошибки постоянно

**Comment by ilyalyo** [comment]
апи обновилось у инста

**Comment by Zoruf** [comment]
так и что дальше будет? Теперь постоянные ошибки? или к нему приспособиться можно?

**Comment by ilyalyo** [comment]
я ж пофиксил. поэтому и закрыл

**Comment by Zoruf** [comment]
А понял
19 окт. 2015 г. 17:42 пользователь "ilyalyo" notifications@github.com
написал:
