### ISSUE TITLE
Америкосы

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#29]
maxMiller_htx
teper voobshe ne zapuskautsya processi, dazhe parsing spiska ne idet, srazu pishet zaversheno
11:29 23/09/2015
maxMiller_htx
v chem problema?? ne rabotaet servis
15:21 27/09/2015
maxMiller_htx
Что делать? Мне другой севис искать или вы исправите эти ошибки, ждать то есть смысл вообще?

**Comment by ilyalyo** [comment]
это 3 недели назад было, и помоему это было связано с тем что он прокси свое не проплатил

**Comment by ilyalyo** [comment]
https://gyazo.com/96a5fa25d54d2351500a86bc73ac33fc
