### ISSUE TITLE
Трабла у чувака

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#30]
Gossip_off
Добрый день, не могу запустить задачу на фолловинг. Выдает ошибку
15:56 30/09/2015
Служба поддержки
Здравствуйте! А что написано в ошибке?
20:47 04/10/2015
Gossip_off
В ошибке написано ошибка

**Comment by ilyalyo** [comment]
это было 2 недели назад

**Comment by Zoruf** [comment]
не, он мне сейчас написал только что в ошибке, значит до сих пор повторяется

**Comment by ilyalyo** [comment]
короч у него 2 дня уже все ок работает, до этого таски не завершались потому что инстаграм возвращал на наши запросы null, это не фиксится
