### ISSUE TITLE
Отписка

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#32]
Появились ограничения по отписке. Цифры разнятся от 250-300 в день. Иначе происходят блокировки акков. Можно сделать по умолчанию рекомендуемый интервал (увеличенный с учетом ограничений) либо, что мне кажется лучше, сделать рекомендуемое ограничение по количеству отписок за 1 раз

**Comment by ilyalyo** [comment]
https://gyazo.com/a6e4ba5931635c2bb5a411dbaff87d4c
вроде у всех и больше работает
пока оставлю открытой
