### ISSUE TITLE
Еще проблемка у чела

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#33]
amquest
Помогите, пожалуйста. Не добавляется ни один аккаунт. 400 Bad request Your browser sent an invalid request.
11:08 21/10/2015
amquest
orce_classic_login=&next=/oauth/authorize/%3Fclient_id%3D6e336200a7f446a78b125602b90989cc%26redirect_uri%3Dhttp%3A//instastellar.su/get_token%26response_type%3Dcode%26scope%3Dlikes%2Bcomments%2Brelationships Pragma: no-cache Set-Cookie:
11:08 21/10/2015
amquest
csrftoken=5d71085120f87b40b2d41a4297b386b1; expires=Wed, 19-Oct-2016 08:04:57 GMT; Max-Age=31449600; Path=/ Vary: Cookie, Accept-Language Content-Length: 0 Connection: keep-alive "

**Comment by ilyalyo** [comment]
эт плохо
но он видимо разобрался, тк акк добавил
