### ISSUE TITLE
Проблема с фоловингом

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#39]
audiovarda
Добрый день. Пытаемся фоловить по конкуренту brovi_resnici_msk от аккаунта brows_evolution- пишет что фоловинг закрытых аккаунтов невозможен. А аккаунт открыт, не приватный. Спасибо.

С этой проблемой уже 2 чел за день пишет

**Comment by ilyalyo** [comment]
короч оказалось что если тот, кого ты хочешь фоловить заблокировал тебя, то ты не можешь с ним никакие действия совершать
