### ISSUE TITLE
Не добавляет акк

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#40]
volnov
Добрый день, не могу добавить свой аккаунт, хотя ввожу верно логин и пароль
23:15 16/10/2015
Служба поддержки
День добрый, Бывает что пароль сбрасывается инстаграмом при первом входе, проверьте на всякий случай еще раз, сброшен ли пароль! И что пишет наш сервис когда не добавляет?
13:40 21/10/2015
volnov
Пароль перепроверял уже много раз. После заполнения логина и пароля долго грузит и в конце пишет "Возможно неправильная пара логин и пароль " . Логин и пароль login - getiphone6today password - blogger

**Comment by ilyalyo** [comment]
проверь подходит ли, у меня чет не логинит

**Comment by Zoruf** [comment]
Проверял, у меня логинится
28 окт. 2015 г. 21:16 пользователь "ilyalyo" notifications@github.com
написал:
