### ISSUE TITLE
Акк не добавляется

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#49]
Antoxa
Добрый день. не могу привязать аккаунт bn_team. В чем причина.
00:02 13/11/2015
Antoxa
Добрый день. Опять проблема, не могу добавить аккаунт krohasib Выдает ошибку. пароль менял.

**Comment by Zoruf** [comment]
kabluchini
здравствуйте! не могу добавить аккаунт выдает ошибку

и еще

**Comment by ilyalyo** [comment]
bn_team сам добавил
krohasib&kabluchini пароли не правильные
