### ISSUE TITLE
Тоже не добавляется

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#52]
Изменил Логин: Diplom39 qwerty1

Виталий
и как, получилось?
28.11.15    

Andrey
Аккаунт с таким логином уже существует,пишет
28.11.15  
Я просто когда только еще заводил ак в Instastellar,наверное забыл его удалить,а после уже создал новый ак,который по сей день использую

**Comment by ilyalyo** [comment]
удалил, пусть снова добавляет
