### ISSUE TITLE
Ошибка andy0696

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#59]
Andy0696
Возникли проблемы с аккаунтами,а именно после удаление аккаунта и его повторного добавления,он добавляется но при действиях(подписки и лайки) выдает ошибку...Сейчас у меня 3 аккаунта не активны из-за этого...

**Comment by ilyalyo** [comment]
чет он пиздит
у него все работает
SELECT \* FROM `progress` WHERE ac_id in (1481,1483,1492,1563,1568,1589)
