### ISSUE TITLE
Ошибка Cyberg

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#61]
Cyberg
Доброе утро. не могу добавить аккаунт от инстаграмма. Пишет ошибка не правильная пара логин пароль. Хотя на сайте инстаграм проверил, все подходит.
05:43 04/12/2015
Служба поддержки
Добрый день, проверьте еще раз в инстаграме, Тк очень часто при первом добавлении аккаунта к нам пароли сбрасывается . Его нужно восстановить и добавить аккаунт еще раз
10:15 04/12/2015
Cyberg
проверил, на инстаграме работает. У вас нет...
10:30 04/12/2015
Служба поддержки
Тогда сейчас проверим в чем дело
10:52 04/12/2015
Cyberg
спасибо,жду

**Comment by ilyalyo** [comment]
старье, он уже успел удалить
