### ISSUE TITLE
Не добавляет аккаунт talex10

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#63]
talex10
Не могу добавить аккаунт(
18:10 04/12/2015
talex10
есть кто тут?
18:10 04/12/2015
talex10
не подключается аккаунт
20:00 04/12/2015
Служба поддержки
Добрый день, какую ошибку выдает?
03:07 05/12/2015
talex10
5xx Server Error

**Comment by ilyalyo** [comment]
пароль слетел у него
