### ISSUE TITLE
Ошибка, которая не пофиксилась - DIMA

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#65]
DIMA
katushka_shop_ua - АККАУНТ НЕ РАБОТАЕТ -ПОСТОЯННАЯ ОШИБКА + ЗАДАНИЯ В НЕКОТОРЫХ ДРУГИХ НЕ ВЫПОЛНЯЮТСЯ ДО КОНЦА , НАПРИМЕР В ЗАДАНИИ 1000 ПОПИСОК - ДЕЛАЕТ 400?

**Comment by ilyalyo** [comment]
это норрм
