### ISSUE TITLE
Сбрасывает пароль - kirabarysheva@mail.ru 

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#72]
Kira_barysheva - Инстовский аккаунт
kirabarysheva@mail.ru - почта

Не может зайти в инстаграм с телефона - сразу сбрасывает пароль, на компьютере все норм. Задачу останавливает прежде чем войти.

**Comment by ilyalyo** [comment]
чет не понял, если она не может войти в инстаграм с телефона, нах она нам пишет, пусть в тех. поддержку инста пишет

**Comment by Zoruf** [comment]
Ну типа после использования нашего сервиса у нее постоянно просит восстановить пароль когда она с трубы входит

**Comment by Zoruf** [comment]
Еще пишет что парсинг стал идти оч долго
