### ISSUE TITLE
Ошибка - nvpp@inbox.ru

### ISSUE THREAD

**Issue by Zoruf** [ilyalyo/insta#79]
nvpp@inbox.ru
Доброго времени суток! На сегодняшний день к сервису привязано 4 моих акк. Я пробовала задавать различные задачи на всех 4х. На мой взгляд ни одна задача не была выполнена. Хотя в статусе указано именно это состояние.
23:16 24/02/2016
nvpp@inbox.ru
Проходя по кнопке "детали", там где должен быть отчет о проделанной работе, пустота. Если я некорректно ставлю задачи, укажите мне на мои ошибки. Если мои задачи невыполнимы, верните мои средства.
23:17 24/02/2016
nvpp@inbox.ru
Уже почти месяц я пытаюсь наладить работу с помощью этого сервиса. Эффект нулевой

**Comment by ilyalyo** [comment]
когда ставит по гео , у нее не парсит, тк гео вообще мало парсит, остальное у нее работает
